######################################################################
# Automatically generated by qmake (2.01a) Sun May 27 20:07:21 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dataapp.h exporttohtml.h searchresult.h ui_exporttohtml.h
FORMS += dataapp.ui searchresult.ui
SOURCES += dataapp.cpp exporttohtml.cpp main.cpp searchresult.cpp
RESOURCES += dataRes.qrc
